### ISSUE TITLE
'Firebase' is a namespace but is used like a type

### ISSUE THREAD

**Issue by tekrazorlr1** [dkrprasetya/simple-firebase-csharp#10]
As the title have suggested, I've imported the asset on Unity Asset store but it simply doesn't work. Within my project I've imported Firebase Database module. 
![image](https://cloud.githubusercontent.com/assets/22879540/22174315/467af6b4-e016-11e6-9498-5f6be5229eea.png)

**Comment by tekrazorlr1** [comment]
The issue has been resolved, it turns out the packages of Firebase Database clashed.

**Comment by kasradzenika** [comment]
fixed here:
https://github.com/dkrprasetya/simple-firebase-unity/pull/11
