### ISSUE TITLE
Pushing large JSON freezes up Unity player

### ISSUE THREAD

**Issue by lokeuei** [dkrprasetya/simple-firebase-csharp#13]
When I try to PUSH a large JSON document, ~900k-1mb in size containing 1,500 -1,600 rows of vector3 position and Quaternion rotation data, the Unity player freezes (goes black) for half a second before gameplay proceeds. I understand that SimpleFirebase uses Coroutines which in concept runs on a separate thread. Do you know why this is not the case? 

Is this a known issue or something you can help resolve?

thanks!

**Comment by dkrprasetya** [comment]
Coroutine is not running on separate thread, reading large JSON will takes time thus may creating hiccups or even blocking the main thread.

I will mark this solved for now as JSON read/write now uses different thread (unless it is WebGL... multithreading in WebGL is not supported).
