### ISSUE TITLE
The asset is not working for me

### ISSUE THREAD

**Issue by Jatapiaro** [dkrprasetya/simple-firebase-csharp#17]
I'm trying to use your example with my project but it never sends anything. The database is empty, could you please upload a simple example with the code in the readme?

THANKS

**Comment by dkrprasetya** [comment]
There is an example written in the readme, and a sample scene is attached in the plugin. Also, don't forget to make sure that your database's url is correct.

If you still have any issue, please make a new issue with a more clearer description of what is the problem, what did you do / steps to reproduce, and so on that may help me or the others help you more precisely.
