### ISSUE TITLE
Incorrect method description on first overload of Firebase.SetValue

### ISSUE THREAD

**Issue by lachlansleight** [dkrprasetya/simple-firebase-csharp#25]
Should read "Calls OnSetSuccess on success", but currently reads "Calls OnUpdateSuccess on success". Also reads "Calls OnUpdateFailed" rather than "Calls OnSetFailed".

Super easy to fix and is pretty annoying until a hypothetical dev decides to start trying random event handlers in desperation ;)

Specifically, line 467 and 468 of file 

https://github.com/dkrprasetya/simple-firebase-unity/blob/master/Assets/SimpleFirebaseUnity/Scripts/Firebase.cs

**Comment by dkrprasetya** [comment]
Hey, I haven't checked this for **a while.** You're right, this is super easy to fix and I've pushed the fix. Thanks for catching this.

**Comment by lachlansleight** [comment]
No worries - but you might also want to update line 466 while you're at it - it still reads "Calls OnUpdateSuccess" etc :P
