### ISSUE TITLE
Cannot find method summary

### ISSUE THREAD

**Issue by KShoukry** [dkrprasetya/simple-firebase-csharp#5]
Hey, in your readme file you say "Every available method is equipped with summary and parameter descriptions" where are they explained cause I cannot seem to find them.

**Comment by dkrprasetya** [comment]
Whoops it doesn't show up? I believe I have written the description of each method. Let me check again.

**Comment by tjjos** [comment]
I can't find them either. Where are we supposed to look for those descriptions?

**Comment by dkrprasetya** [comment]
Found the problem. I forgot to build and include the .xml for displaying the .dll's content summaries. 
I will close the issue after the update has been published on Asset Store.

Thanks for reporting!

**Comment by dkrprasetya** [comment]
The fix has been published on the AssetStore.
