### ISSUE TITLE
OnPushSuccess Data is always empty

### ISSUE THREAD

**Issue by ZenithCode** [dkrprasetya/simple-firebase-csharp#8]
Hi,

The callback you receive on a successfull push has a 'DataSnapshot' parameter but this is always empty.

Is this a bug or am I doing something wrong?

Thanks,

**Comment by ZenithCode** [comment]
OnPushFailed callback has parameter 'FirebaseError.Data' which is also empty.

My goal is to know what data has been successfully sent or failed to be sent.

Thanks,

**Comment by dkrprasetya** [comment]
DataSnapshot is a container for the returned Data from the REST requests. So it should contain the json as it is, just as documented on https://firebase.google.com/docs/reference/rest/database/ .

According to the documentation, a successful push request will return a json with key "name" which is the generated string key for your pushed data. Have you tried to output its _RawJson_?  I have tested it and it seems working fine here.

For the **FirebaseError**, _Data_ is a variable inherited from **Exception** class. I don't know what it contains, but from the implemented _Message_ and _Status_ getter you will get the information why your request failed, which may helps on your case.
