### ISSUE TITLE
Could not parse auth token. (401)

### ISSUE THREAD

**Issue by Hyper00** [dkrprasetya/simple-firebase-csharp#9]
1. [OBSERVER] FirebaseObserver on /lastUpdate started!
2. Firebase endpoint: https://flicker-d6bfb.firebaseio.com/.json
3. Firebase key: 
4. Firebase fullKey: 
5. Firebase child key: temporary
6. Firebase child fullKey: /temporary
7. [WARNING] There is one invalid request below which will gives error, only for example on error handling.
8. ==== Wait for seconds 15f ======
9. [ERR] Set from key: <>, Could not parse auth token. (401)
10. [ERR] Push from key: </broadcasts>, Could not parse auth token. (401)
11. [ERR] Get from key: <>,  Could not parse auth token. (401)
12. [ERR] Update from key: </layout>, Could not parse auth token. (401)
13. [ERR] Get from key: </layout>,  Could not parse auth token. (401)
14. [ERR] Get from key: <>,  orderBy must be defined when other query parameters are defined (400)
15. ==== Wait over... ====
16. ==== Wait for seconds 15f ======
17. [ERR] Get from key: <>,  Could not parse auth token. (401)
18. [ERR] Get from key: </scores>,  Could not parse auth token. (401)
19. [ERR] Get from key: <>,  Could not parse auth token. (401)
20. [ERR] Get from key: </temporary>,  Could not parse auth token. (401)
21. [ERR] Get from key: </temporary>,  Could not parse auth token. (401)
22. [ERR] GetRules,  Could not parse auth token. (401)
23. [ERR] Push from key: </broadcasts>, Could not parse auth token. (401)
24. ==== Wait over... ====
25. 'broadcasts' node is deleted silently.
26. ==== Wait for seconds 15f ======
27. [ERR] Get from key: <>,  Could not parse auth token. (401)
28. [ERR] Del from key: </temporary>, Could not parse auth token. (401)
29. [ERR] Get from key: <>,  Could not parse auth token. (401)
30. ==== Wait over... ====
31. [OBSERVER] FirebaseObserver on /lastUpdate stopped!

I can not understand what's wrong ?! I enter the link and API key for the Web application - but get back an error. What have I missed?

Firebase firebase = Firebase.CreateNew ( "flicker-d6bfb.firebaseio.com", "AIzaSyCz_nL5qA *** okw8 *** krVp9Jm2 *******");

**Comment by Hyper00** [comment]
Prompt please, it only works on the old version of the site? I just want to create on the same basis Authorization and may turn file sharing ... I hope)))

Prompt please, it only works on the old version of the site? I just want to create on the same basis Authorization and may turn file sharing ... I hope)))So whether the work created by the project at the new site will firebase or just old. I just met somewhere like that, but I do not remember in this component is the need or do not need?

https://console.firebase.google.com/project/flicker-d6bfb/database/data

**Comment by dkrprasetya** [comment]
Are you entering the right secret key? You should use the secret key provided on Database tab.

<img width="1205" alt="firebase-database-secret-sample" src="https://cloud.githubusercontent.com/assets/5259029/21472245/b4ca51c8-cb12-11e6-8029-213274d3f803.png">

**Comment by Hyper00** [comment]
Точно!! я про это забыл, то есть изначально не верно было понял)) thank you very much!

By the way, you do not know how to implement authentication REST method? And as I pologayu plug in your old version of authorization ... I wonder how long it will still work.

And if it is not long left to live ... then I think need to make a new version on the REST API. And for the storage of files.

All the same, recently released the official version, but only under unity3d mobile it works well for PC and other platforms to understand and write laziness ... that I think may be able to make time.
ps if the customer agree to create a copy of the type viber, skype

**Comment by nicholasareed** [comment]
The Database link and Legacy Secret creation has moved, it is now under "Service Accounts" in Project Settings.
